Vagrant.configure("2") do |config|
  config.vm.box = "liaoya/alpine"
  config.vm.box_check_update = false
  config.vm.synced_folder "..", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.name = "alpine"
    vb.cpus = 1
    vb.memory = 256
    vb.customize ["modifyvm", :id, "--vram", "16"]
  end
end
